/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    properties: Property;
    'room-types': RoomType;
    amenities: Amenity;
    'nearby-places': NearbyPlace;
    testimonials: Testimonial;
    faqs: Faq;
    'community-posts': CommunityPost;
    founders: Founder;
    media: Media;
    leads: Lead;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    properties: PropertiesSelect<false> | PropertiesSelect<true>;
    'room-types': RoomTypesSelect<false> | RoomTypesSelect<true>;
    amenities: AmenitiesSelect<false> | AmenitiesSelect<true>;
    'nearby-places': NearbyPlacesSelect<false> | NearbyPlacesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'community-posts': CommunityPostsSelect<false> | CommunityPostsSelect<true>;
    founders: FoundersSelect<false> | FoundersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'about-page': AboutPage;
    'community-page': CommunityPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'community-page': CommunityPageSelect<false> | CommunityPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * The property itself — address, description and photos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties".
 */
export interface Property {
  id: number;
  name: string;
  /**
   * Used in the web address. Lower case, words separated by hyphens.
   */
  slug: string;
  /**
   * e.g. "Mitra Enclave, Sector P7"
   */
  locality: string;
  city: string;
  /**
   * Full postal address, as it should appear in the footer.
   */
  addressLine: string;
  /**
   * Google Maps embed link. In Maps: Share → Embed a map → copy the src="…" value only.
   */
  mapEmbedUrl?: string | null;
  /**
   * One or two sentences. Used on the home page and in search results.
   */
  shortDescription: string;
  /**
   * The longer write-up on the property page.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The main photo of the building.
   */
  heroImage?: (number | null) | Media;
  /**
   * Common areas, study room, kitchen, terrace.
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Facilities available across the building.
   */
  amenities?: (number | Amenity)[] | null;
  /**
   * Visitor policy, timings, anything residents agree to.
   */
  houseRules?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Photos used across the site. Every upload needs a description.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe what is in the photo, e.g. "Single room with study table by the window". Read aloud to visually impaired visitors and used by search engines.
   */
  alt: string;
  /**
   * Optional. Shown under the photo in galleries.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    gallery?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Facilities that can be attached to the property or a room.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities".
 */
export interface Amenity {
  id: number;
  /**
   * Shown exactly as typed, e.g. "High-speed Wi-Fi".
   */
  name: string;
  category: 'room' | 'building' | 'services' | 'safety';
  /**
   * Which icon to draw. Names match the site’s icon set.
   */
  iconKey:
    | 'check'
    | 'security'
    | 'securityCheck'
    | 'metro'
    | 'pin'
    | 'campus'
    | 'hospital'
    | 'shopping'
    | 'wifi'
    | 'power'
    | 'water'
    | 'housekeeping'
    | 'inclusive'
    | 'community'
    | 'opportunity'
    | 'chat'
    | 'clock';
  /**
   * Lower numbers appear first.
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The three room options. Change availability here to update the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "room-types".
 */
export interface RoomType {
  id: number;
  /**
   * e.g. "Single room", "Double sharing".
   */
  name: string;
  slug: string;
  property: number | Property;
  /**
   * How many people share the room.
   */
  occupancy: number;
  /**
   * Drives the badge on the website.
   */
  availability: 'available' | 'limited' | 'unavailable';
  /**
   * One or two sentences describing who the room suits.
   */
  summary: string;
  /**
   * What comes with the room, e.g. "Study table and chair".
   */
  furnishings?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers appear first.
   */
  displayOrder?: number | null;
  /**
   * Rupees per month.
   */
  monthlyRent?: number | null;
  /**
   * Rupees, refundable.
   */
  securityDeposit?: number | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Universities, metro stations, hospitals and markets shown on the home and contact pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nearby-places".
 */
export interface NearbyPlace {
  id: number;
  /**
   * Full name, e.g. "Galgotias College of Engineering".
   */
  name: string;
  category: 'university' | 'metro' | 'hospital' | 'shopping';
  /**
   * With the unit, exactly as it should read: "300 m", "3.5 km".
   */
  distance: string;
  /**
   * Optional qualifier, e.g. "About a three-minute walk". Shown under the name.
   */
  note?: string | null;
  /**
   * Draws the distance in orange. Use sparingly — for the metro and the hospitals.
   */
  highlight?: boolean | null;
  /**
   * Lower numbers appear first, usually nearest first.
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Quotes from residents. Get written permission before publishing a name.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  /**
   * College and year, or "Parent". Shown under the name.
   */
  context?: string | null;
  /**
   * Their words. Keep it to two or three sentences.
   */
  quote: string;
  photo?: (number | null) | Media;
  /**
   * Featured quotes appear on the home page.
   */
  featured?: boolean | null;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Answers shown on the FAQ page. Plain language beats policy language.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: 'rent' | 'rooms' | 'moving' | 'rules' | 'food' | 'general';
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Events, match nights, festivals — anything worth showing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-posts".
 */
export interface CommunityPost {
  id: number;
  title: string;
  date: string;
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Shown on the About page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "founders".
 */
export interface Founder {
  id: number;
  name: string;
  /**
   * e.g. "Founder", "Operations".
   */
  role: string;
  /**
   * Two or three sentences — where they are from, what they did before, why student housing. This is the part parents read.
   */
  bio: string;
  photo?: (number | null) | Media;
  linkedinUrl?: string | null;
  email?: string | null;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Enquiries from the website, newest first. Use Filters to narrow by status — start with "New".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  type: 'booking' | 'contact';
  /**
   * Update as you work through it.
   */
  status: 'new' | 'contacted' | 'visit-booked' | 'converted' | 'lost';
  fullName: string;
  /**
   * Ten digits, without +91.
   */
  phone: string;
  email?: string | null;
  roomType?: ('single' | 'double' | 'triple' | 'unsure') | null;
  /**
   * As submitted, e.g. "2026-07".
   */
  moveInMonth?: string | null;
  /**
   * Contact form only.
   */
  subject?: ('booking' | 'visit' | 'parent' | 'other') | null;
  message?: string | null;
  /**
   * Which page the enquiry came from. Set automatically.
   */
  source?: string | null;
  /**
   * Your notes. Never shown to the enquirer.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Shown in the admin panel and on audit trails.
   */
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'properties';
        value: number | Property;
      } | null)
    | ({
        relationTo: 'room-types';
        value: number | RoomType;
      } | null)
    | ({
        relationTo: 'amenities';
        value: number | Amenity;
      } | null)
    | ({
        relationTo: 'nearby-places';
        value: number | NearbyPlace;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'community-posts';
        value: number | CommunityPost;
      } | null)
    | ({
        relationTo: 'founders';
        value: number | Founder;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties_select".
 */
export interface PropertiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  locality?: T;
  city?: T;
  addressLine?: T;
  mapEmbedUrl?: T;
  shortDescription?: T;
  description?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  amenities?: T;
  houseRules?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "room-types_select".
 */
export interface RoomTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  property?: T;
  occupancy?: T;
  availability?: T;
  summary?: T;
  furnishings?:
    | T
    | {
        item?: T;
        id?: T;
      };
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  displayOrder?: T;
  monthlyRent?: T;
  securityDeposit?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities_select".
 */
export interface AmenitiesSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  iconKey?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nearby-places_select".
 */
export interface NearbyPlacesSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  distance?: T;
  note?: T;
  highlight?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  context?: T;
  quote?: T;
  photo?: T;
  featured?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-posts_select".
 */
export interface CommunityPostsSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  excerpt?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "founders_select".
 */
export interface FoundersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  photo?: T;
  linkedinUrl?: T;
  email?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        gallery?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  fullName?: T;
  phone?: T;
  email?: T;
  roomType?: T;
  moveInMonth?: T;
  subject?: T;
  message?: T;
  source?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Phone, email, WhatsApp and address used across the whole site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * As shown, e.g. "+91 82734 58926".
   */
  phoneDisplay: string;
  /**
   * Digits only with country code, for the dial link: 918273458926
   */
  phoneDigits: string;
  email: string;
  /**
   * WhatsApp number, digits only with country code.
   */
  chatNumber: string;
  /**
   * Invite link for the WhatsApp community group. Powers the Community page — leave empty and that button stays hidden.
   */
  chatCommunityUrl?: string | null;
  addressLine1: string;
  addressLine2: string;
  /**
   * e.g. "9 am – 8 pm, daily".
   */
  visitingHours: string;
  /**
   * Leave empty until the handles are live — the footer says "coming soon" when there are none.
   */
  socialLinks?:
    | {
        platform: 'instagram' | 'facebook' | 'linkedin' | 'youtube';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hero copy and the home page sections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  eyebrow: string;
  /**
   * The single biggest line on the site. Keep it short.
   */
  title: string;
  subtitle: string;
  heroImage?: (number | null) | Media;
  /**
   * The short list under the hero buttons.
   */
  trustPoints?:
    | {
        iconKey:
          | 'check'
          | 'security'
          | 'securityCheck'
          | 'metro'
          | 'pin'
          | 'campus'
          | 'hospital'
          | 'shopping'
          | 'wifi'
          | 'power'
          | 'water'
          | 'housekeeping'
          | 'inclusive'
          | 'community'
          | 'opportunity'
          | 'chat'
          | 'clock';
        /**
         * Optional bold opening, e.g. "300 m".
         */
        lead?: string | null;
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The "Why Safe Haven" band.
   */
  whyPoints?:
    | {
        iconKey:
          | 'check'
          | 'security'
          | 'securityCheck'
          | 'metro'
          | 'pin'
          | 'campus'
          | 'hospital'
          | 'shopping'
          | 'wifi'
          | 'power'
          | 'water'
          | 'housekeeping'
          | 'inclusive'
          | 'community'
          | 'opportunity'
          | 'chat'
          | 'clock';
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Numbered automatically in the order listed.
   */
  howItWorks?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  title: string;
  /**
   * Why you started Safe Haven, in three or four sentences. This does more work than any feature list on the site.
   */
  intro: string;
  /**
   * Leave empty while the real numbers are small — the strip hides itself.
   */
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  values?:
    | {
        iconKey:
          | 'check'
          | 'security'
          | 'securityCheck'
          | 'metro'
          | 'pin'
          | 'campus'
          | 'hospital'
          | 'shopping'
          | 'wifi'
          | 'power'
          | 'water'
          | 'housekeeping'
          | 'inclusive'
          | 'community'
          | 'opportunity'
          | 'chat'
          | 'clock';
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-page".
 */
export interface CommunityPage {
  id: number;
  title: string;
  intro: string;
  /**
   * Small print under the join button, e.g. "Free · leave any time".
   */
  joinNote?: string | null;
  /**
   * What circulates in the group.
   */
  whatGetsShared?:
    | {
        iconKey:
          | 'check'
          | 'security'
          | 'securityCheck'
          | 'metro'
          | 'pin'
          | 'campus'
          | 'hospital'
          | 'shopping'
          | 'wifi'
          | 'power'
          | 'water'
          | 'housekeeping'
          | 'inclusive'
          | 'community'
          | 'opportunity'
          | 'chat'
          | 'clock';
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  groundRules?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  phoneDisplay?: T;
  phoneDigits?: T;
  email?: T;
  chatNumber?: T;
  chatCommunityUrl?: T;
  addressLine1?: T;
  addressLine2?: T;
  visitingHours?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  subtitle?: T;
  heroImage?: T;
  trustPoints?:
    | T
    | {
        iconKey?: T;
        lead?: T;
        text?: T;
        id?: T;
      };
  whyPoints?:
    | T
    | {
        iconKey?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  howItWorks?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  values?:
    | T
    | {
        iconKey?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-page_select".
 */
export interface CommunityPageSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  joinNote?: T;
  whatGetsShared?:
    | T
    | {
        iconKey?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  groundRules?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}